version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: inventory-management-hosted
    container_name: app
    env_file: .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_URI: ${DB_URI}
      CONNECTION_STRING: ${CONNECTION_STRING}
      PASSWORD: ${PASSWORD}
      EMAIL: ${EMAIL}
    ports:
      - "8000:8080"
    restart: unless-stopped
    networks:
      - inventory-management-network

networks:
  inventory-management-network:
    driver: bridge
